apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: bitnami/rabbitmq:3.7
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 4369
            - containerPort: 5672
            - containerPort: 25672
            - containerPort: 15672
