apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-4369
      port: 4369
      targetPort: 4369
    - name: rabbitmq-5672
      port: 5672
      targetPort: 5672
    - name: rabbitmq-25672
      port: 25672
      targetPort: 25672
    - name: rabbitmq-15672
      port: 15672
      targetPort: 15672

