name: FastAPI-Celery app deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: |
        # Build the docker image from Dockerfile
        docker build . -t fastapi-celery:latest

        # Docker login and push
        docker login -u ${{ secrets.USER }} -p ${{ secrets.PASSWORD }}
        docker tag fastapi-celery:latest ${{ secrets.USER }}/fastapi-celery:latest
        docker push ${{ secrets.USER }}/fastapi-celery:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  

      # Updating AWS EKS Cluster
    - name: Updating AWS EKS Cluster
      run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.AWS_EKS_CLUSTER_NAME }}

    # Deploying K8s Configs
    - name: K8s Configs Deployment
      run: kubectl apply -f k8s/
